//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBandTour_UH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Conciertos
    {
        public int Id { get; set; }
        public string Codigo { get; set; }
        public string Banda { get; set; }
        public string Genero { get; set; }
        public string Fecha { get; set; }
        public string Hora { get; set; }
        public string Pais { get; set; }
        public string Direccion { get; set; }
    }
}
