//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBandTour_UH.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BD_PaisesEntities : DbContext
    {
        public BD_PaisesEntities()
            : base("name=BD_PaisesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Paises> Paises { get; set; }
    
        public virtual ObjectResult<pr_ConsultarPais_Result> pr_ConsultarPais()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_ConsultarPais_Result>("pr_ConsultarPais");
        }
    
        public virtual int pr_InsertarPais(string pais, string capital, Nullable<long> poblacion, ObjectParameter resultado)
        {
            var paisParameter = pais != null ?
                new ObjectParameter("Pais", pais) :
                new ObjectParameter("Pais", typeof(string));
    
            var capitalParameter = capital != null ?
                new ObjectParameter("Capital", capital) :
                new ObjectParameter("Capital", typeof(string));
    
            var poblacionParameter = poblacion.HasValue ?
                new ObjectParameter("Poblacion", poblacion) :
                new ObjectParameter("Poblacion", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_InsertarPais", paisParameter, capitalParameter, poblacionParameter, resultado);
        }
    }
}
