//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyBandTour_UH.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class BD_MyBandTourEntities1 : DbContext
    {
        public BD_MyBandTourEntities1()
            : base("name=BD_MyBandTourEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Conciertos> Conciertos { get; set; }
    
        public virtual ObjectResult<pr_BuscarConcierto_Result> pr_BuscarConcierto(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("codigo", codigo) :
                new ObjectParameter("codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_BuscarConcierto_Result>("pr_BuscarConcierto", codigoParameter);
        }
    
        public virtual ObjectResult<pr_BuscarPorNombre_Result> pr_BuscarPorNombre(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_BuscarPorNombre_Result>("pr_BuscarPorNombre", nombreParameter);
        }
    
        public virtual ObjectResult<pr_ConsultarConciertos_Result> pr_ConsultarConciertos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pr_ConsultarConciertos_Result>("pr_ConsultarConciertos");
        }
    
        public virtual int pr_EliminarConcierto(string codigo)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pr_EliminarConcierto", codigoParameter);
        }
    
        public virtual ObjectResult<string> pr_InsertarConcierto(string codigo, string banda, string genero, Nullable<System.DateTime> fecha, Nullable<System.TimeSpan> hora, string pais, string direccion, ObjectParameter resultado)
        {
            var codigoParameter = codigo != null ?
                new ObjectParameter("Codigo", codigo) :
                new ObjectParameter("Codigo", typeof(string));
    
            var bandaParameter = banda != null ?
                new ObjectParameter("Banda", banda) :
                new ObjectParameter("Banda", typeof(string));
    
            var generoParameter = genero != null ?
                new ObjectParameter("Genero", genero) :
                new ObjectParameter("Genero", typeof(string));
    
            var fechaParameter = fecha.HasValue ?
                new ObjectParameter("Fecha", fecha) :
                new ObjectParameter("Fecha", typeof(System.DateTime));
    
            var horaParameter = hora.HasValue ?
                new ObjectParameter("Hora", hora) :
                new ObjectParameter("Hora", typeof(System.TimeSpan));
    
            var paisParameter = pais != null ?
                new ObjectParameter("Pais", pais) :
                new ObjectParameter("Pais", typeof(string));
    
            var direccionParameter = direccion != null ?
                new ObjectParameter("Direccion", direccion) :
                new ObjectParameter("Direccion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("pr_InsertarConcierto", codigoParameter, bandaParameter, generoParameter, fechaParameter, horaParameter, paisParameter, direccionParameter, resultado);
        }
    }
}
